@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package cn.dancingsnow.neoecoae.recipe;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;