name: Release Neo ECO AE Extension
on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-disabled: true

      - name: Clean Gradle state
        run: rm -rf .gradle build .ci-gradle-home

      - name: Show Gradle version
        run: ./gradlew --version

      - name: Copy Guide Book
        run: ./gradlew copyGuidebook --no-daemon --stacktrace --no-parallel --gradle-user-home .ci-gradle-home

      - name: Build with Gradle
        run: ./gradlew build --no-daemon --stacktrace --no-parallel --gradle-user-home .ci-gradle-home

      - name: Prepare Release Jar
        run: ./gradlew prepareReleaseJar --no-daemon --stacktrace --no-parallel --gradle-user-home .ci-gradle-home

      - name: Read Properties
        id: 'properties'
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: gradle.properties
          properties: 'mod_id mod_name mod_version'

      - name: Get Version
        id: var
        run: |
          echo "version=${{ steps.properties.outputs.mod_version }}" >> $GITHUB_OUTPUT

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: "${{ steps.properties.outputs.mod_name }} ${{ steps.var.outputs.version }}"
          path: build/libs/${{ steps.properties.outputs.mod_id }}-${{ steps.var.outputs.version }}.jar

      - name: Publish Mod
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          name: "${{ steps.properties.outputs.mod_name }} v${{ steps.var.outputs.version }}"
          version: ${{ steps.var.outputs.version }}
          version-type: release
          github-token: ${{ secrets.GITHUB_TOKEN }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          game-versions: |
            1.20.1

          files: |
            build/libs/${{ steps.properties.outputs.mod_id }}-${{ steps.var.outputs.version }}.jar
            build/libs/${{ steps.properties.outputs.mod_id }}-${{ steps.var.outputs.version }}-sources.jar
